// <auto-generated />
using DoctorAppointmentApp.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoctorAppointmentApp.Migrations
{
    [DbContext(typeof(DoctorAppointmentContext))]
    partial class DoctorAppointmentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DoctorAppointmentApp.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorID"), 1L, 1);

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Experience")
                        .HasColumnType("real");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DoctorID");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            DoctorID = 101,
                            Available = true,
                            DoctorName = "Ramu",
                            Experience = 5.5f,
                            Specialization = "Heart"
                        },
                        new
                        {
                            DoctorID = 102,
                            Available = true,
                            DoctorName = "Samu",
                            Experience = 8.5f,
                            Specialization = "Skin"
                        },
                        new
                        {
                            DoctorID = 103,
                            Available = true,
                            DoctorName = "Kamu",
                            Experience = 2f,
                            Specialization = "Eye"
                        },
                        new
                        {
                            DoctorID = 104,
                            Available = true,
                            DoctorName = "Tamu",
                            Experience = 7f,
                            Specialization = "Heart"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
